[package]
edition = "2024"
name = "test-base"
version = "0.1.0"
publish = false

[features]
hv = ["somehal/hv"]

[dependencies]
log = "0.4"
somehal = {workspace = true}
buddy_system_allocator = "0.11"

[[test]]
harness = false
name = "test"
