[package]
edition = "2024"
name = "test-gicv2"
publish = false
version = "0.1.0"

[features]
hv = ["test-base/hv"]

[dependencies]
arm-gic-driver = {workspace = true}
log = "0.4"
test-base = {workspace = true}
spin = "0.10"

[[test]]
harness = false
name = "test"
